import "dotenv/config";
import { readFile } from "node:fs/promises";
import { request } from "node:https";

const getReviewed = async () => {
  try {
    // Read the review output
    const review = await readFile("review_output.md", "utf8");

    // Create comment body with header and footer
    const commentBody = `## 🤖 Gemini AI Code Review

${review}

---
*This review was automatically generated by Gemini AI. Please use your judgment and verify all suggestions.*

<details>
<summary>💡 How to use this review</summary>

- **Critical issues** should be addressed before merging
- **Suggestions** are optional improvements to consider
- **Security concerns** should be carefully evaluated
- Use the review as a starting point for discussion with your team

</details>`;
    return {
      data: commentBody,
    };
  } catch (_e) {
    // for typescript only
    const e = _e as unknown as Error;
    console.error("❌ Error posting comment:", e.message);
    process.exit(1);
  }
};

export { getReviewed };
