name: Auto PR Comments

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add multiple comments to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "👋 Thanks for opening this PR!",
            });
